//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arenda_14
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARENDA_lastEntities : DbContext
    {
        public ARENDA_lastEntities()
            : base("name=ARENDA_lastEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Аренда> Аренда { get; set; }
        public virtual DbSet<Организации> Организации { get; set; }
        public virtual DbSet<ТорговыеМеста> ТорговыеМеста { get; set; }
    }
}
