//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arenda_14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аренда
    {
        public int КодУчётаАренды { get; set; }
        public int КодОрганизации { get; set; }
        public int КодТорговогоМеста { get; set; }
        public string Договор { get; set; }
        public Nullable<System.DateTime> ДатаЗаключенияДоговора { get; set; }
        public Nullable<System.DateTime> ДатаОкончанияДоговора { get; set; }
        public Nullable<bool> Оплачено { get; set; }
        public Nullable<System.DateTime> ДатаЗачисления { get; set; }
        public Nullable<System.DateTime> ОплатаПоДоговору { get; set; }
        public Nullable<float> СуммаОплаты { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Организации Организации { get; set; }
        public virtual ТорговыеМеста ТорговыеМеста { get; set; }
    }
}
